[build]
command = "astro build"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/.netlify/images/*"
to = "https://www.thecocktaildb.com/images/media/drink/:splat"
status = 200
force = true
